# Generated by Django 2.2.12 on 2020-05-23 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200518_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_one_Photo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_one_category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_one_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_one_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_three_Photo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_three_category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_three_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_three_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_two_Photo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_two_category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_two_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_two_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_five',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_four',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_six',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_three',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_two',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_Three',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_five',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_four',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_six',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_two',
        ),
    ]
