# Generated by Django 2.2.12 on 2020-05-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20200515_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Type_of_creation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='made_for',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
