# Generated by Django 2.2.12 on 2020-05-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_auto_20200517_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='button_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='button_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
