# Generated by Django 2.2.12 on 2020-05-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Type_of_creation',
            field=models.CharField(blank=True, choices=[('Poster', 'Poster'), ('UX', 'UX'), ('Brand', 'Brand')], max_length=100, null=True),
        ),
    ]
