# Generated by Django 2.2.12 on 2020-05-23 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_auto_20200519_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='related_one_Photo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_one_category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_one_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_one_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_three_Photo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_three_category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_three_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_three_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_two_Photo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_two_category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_two_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='related_two_title',
        ),
    ]
