# Generated by Django 2.2.12 on 2020-04-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
