# Generated by Django 2.2.12 on 2020-05-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200517_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
