# Generated by Django 2.2.12 on 2020-05-19 05:35

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blog', '0007_auto_20200518_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='blogtags', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
