# Generated by Django 2.2.12 on 2020-05-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200521_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text_five',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_four',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_six',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_three',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_two',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_Three',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_five',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_four',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_six',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_two',
        ),
    ]
